name: Build APK (No Gradle Wrapper)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget unzip gradle

      - name: Download ZIP
        run: |
          wget -O source.zip https://github.com/ducminh11102012/build-apk/releases/download/1/pureread-lite.zip

      - name: Unzip
        run: |
          unzip source.zip -d src
          ls -R src

      - name: Find project root
        run: |
          echo "Searching for Android project..."
          PROJECT_DIR=$(find src -name "build.gradle*" -exec dirname {} \; | head -n 1)

          if [ -z "$PROJECT_DIR" ]; then
            echo "ERROR: No build.gradle found!"
            exit 1
          fi

          echo "Project dir: $PROJECT_DIR"
          echo $PROJECT_DIR > project_dir.txt

      - name: Build Debug APK (system gradle)
        run: |
          PROJECT_DIR=$(cat project_dir.txt)
          cd "$PROJECT_DIR"

          echo "Building in $PROJECT_DIR"

          gradle assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            src/**/build/outputs/apk/debug/*.apk
